"""
run_all.py — run every econometric battery test in sequence.

Each test writes a JSON to checkin/econometric_battery/. After all complete,
a REPORT.md is generated summarising pass/fail and key statistics.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
from _battery import BATTERY_CHECKIN_DIR  # noqa: E402

TESTS = [
    ("test_01_stationarity.py",            "Panel unit-root tests"),
    ("test_02_cross_section_dependence.py", "Cross-sectional dependence"),
    ("test_03_cointegration.py",           "Panel cointegration"),
    ("test_04_serial_correlation.py",      "Panel serial correlation"),
    ("test_05_robust_se.py",               "Robust standard errors"),
    ("test_06_exogeneity.py",              "Exogeneity battery"),
    ("test_07_specification.py",           "Specification / functional form"),
    ("test_08_structural_breaks.py",       "Structural breaks"),
    ("test_09_influence.py",               "Influence diagnostics"),
    ("test_10_robust_regression.py",       "Outlier-robust estimators"),
    ("test_11_multiple_testing.py",        "Multiple testing corrections"),
    ("test_12_dynamic_panels.py",          "Dynamic panel / GMM"),
    ("test_13_modern_did.py",              "Modern DiD"),
    ("test_14_synthetic_control.py",       "Synthetic control"),
    ("test_15_cross_validation.py",        "Cross-validation"),
    ("test_16_functional_form.py",         "Variable transformations"),
    ("test_17_sample_composition.py",      "Sample composition"),
    ("test_18_measurement_error.py",       "Measurement-error correction"),
    ("test_19_placebo.py",                 "Placebo tests"),
    ("test_20_predictive_validity.py",     "Predictive validity"),
]


def run_one(script, description):
    print()
    print("#" * 72)
    print(f"# {script}: {description}")
    print("#" * 72)
    t0 = time.time()
    path = os.path.join(HERE, script)
    r = subprocess.run([sys.executable, path], cwd=os.path.dirname(os.path.dirname(HERE)))
    dt = time.time() - t0
    exit_ok = r.returncode == 0
    # Prefer substantive verdict from the checkin JSON when present; fall
    # back to exit code only when the script didn't write a verdict_pass.
    json_path = os.path.join(
        BATTERY_CHECKIN_DIR, script.replace("test_", "").replace(".py", ".json")
    )
    verdict_pass = None
    if exit_ok and os.path.exists(json_path):
        try:
            with open(json_path) as fh:
                data = json.load(fh)
            if isinstance(data.get("verdict_pass"), bool):
                verdict_pass = data["verdict_pass"]
        except (json.JSONDecodeError, OSError):
            pass
    ok = exit_ok and (verdict_pass if verdict_pass is not None else True)
    return {"script": script, "description": description, "ok": ok,
            "exit_ok": exit_ok, "verdict_pass": verdict_pass,
            "elapsed_s": float(dt)}


def render_report(results):
    md = []
    md.append("# Econometric Battery — Summary Report")
    md.append("")
    md.append("Auto-generated by `scripts/econometric_battery/run_all.py`. "
              "Reads JSON outputs from `checkin/econometric_battery/`.")
    md.append("")
    md.append("## Test inventory")
    md.append("")
    md.append("| # | Test | Description | Runtime (s) | Status |")
    md.append("|---|------|-------------|-------------|--------|")
    for i, r in enumerate(results, 1):
        status = "✓" if r["ok"] else "✗"
        md.append(f"| {i:02d} | `{r['script']}` | {r['description']} | "
                  f"{r['elapsed_s']:.1f} | {status} |")
    md.append("")
    # Pull headline statistics from each JSON
    md.append("## Headline statistics by test")
    md.append("")
    for r in results:
        json_path = os.path.join(
            BATTERY_CHECKIN_DIR,
            r["script"].replace("test_", "").replace(".py", ".json")
        )
        if not os.path.exists(json_path):
            continue
        with open(json_path) as fh:
            try:
                data = json.load(fh)
            except json.JSONDecodeError:
                continue
        md.append(f"### {r['script']} — {r['description']}")
        md.append("")
        md.append(_format_summary(data))
        md.append("")
    return "\n".join(md)


def _format_summary(d, depth=0, max_depth=2):
    if depth > max_depth:
        return ""
    out = []
    if isinstance(d, dict):
        for k, v in d.items():
            if k == "script":
                continue
            if isinstance(v, (int, float, str, bool)):
                out.append(f"- **{k}**: `{v}`")
            elif isinstance(v, list) and v and isinstance(v[0], (int, float, str)):
                snippet = ", ".join(f"`{x}`" for x in v[:5])
                if len(v) > 5:
                    snippet += f" ... ({len(v)} total)"
                out.append(f"- **{k}**: {snippet}")
            elif isinstance(v, dict) and depth < max_depth:
                out.append(f"- **{k}**:")
                sub = _format_summary(v, depth=depth + 1, max_depth=max_depth)
                if sub:
                    out.append("  " + sub.replace("\n", "\n  "))
    return "\n".join(out)


def main():
    print("=" * 72)
    print("ECONOMETRIC BATTERY — Comprehensive test suite")
    print(f"  Tests: {len(TESTS)}")
    print(f"  Output dir: {BATTERY_CHECKIN_DIR}")
    print("=" * 72)

    results = [run_one(s, d) for s, d in TESTS]

    print()
    print("=" * 72)
    print("SUMMARY")
    print("=" * 72)
    for r in results:
        tag = "[ok]" if r["ok"] else "[FAIL]"
        print(f"  {tag:<7} {r['script']:<40} ({r['elapsed_s']:5.1f}s)  {r['description']}")

    # Write the report
    report_path = os.path.join(HERE, "REPORT.md")
    with open(report_path, "w") as fh:
        fh.write(render_report(results))
    print()
    print(f"Wrote: {report_path}")


if __name__ == "__main__":
    main()
