"""
What share of world population the 185-country panel covers, 2015.

Rhetorical mentions of the panel's scope ("what 185 countries did") are
easier to read as a population share than a raw country count. This
produces that share so it can be cited in place of the raw count.

Data sources:
  - Panel country list: checkin/summary_stats.json -> country_lists.full_panel
    (produced by scripts/tables/summary_stats.py)
  - Population: wcde/data/processed/population_2015.csv (WCDE v3, scenario 2,
    year 2015, summed across age/sex/education; includes a "world" row).
    Generated by wcde/scripts/build_population_2015.py from the raw
    pop_both.csv, which is not shipped to the public replication repo.

Output: checkin/panel_world_pop_share.json
"""

import json
import os
import sys

import pandas as pd

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(SCRIPT_DIR))
from _shared import REPO_ROOT, CHECKIN, write_checkin

YEAR = 2015


def main():
    with open(os.path.join(CHECKIN, "summary_stats.json")) as f:
        panel_countries = json.load(f)["country_lists"]["full_panel"]

    pop_path = os.path.join(REPO_ROOT, "wcde", "data", "processed",
                             "population_2015.csv")
    pop = pd.read_csv(pop_path).set_index("country")["population_thousands"]

    panel_lower = [c.lower() for c in panel_countries]
    missing = [c for c in panel_lower if c not in pop.index]
    if missing:
        raise ValueError(f"Panel countries missing from population file: {missing}")

    panel_pop = pop.reindex(panel_lower).sum()
    world_pop = pop.loc["world"]
    pct = 100 * panel_pop / world_pop

    out = {
        "numbers": {
            "year": YEAR,
            "panel_countries": len(panel_countries),
            "panel_population_thousands": round(float(panel_pop), 1),
            "world_population_thousands": round(float(world_pop), 1),
            "panel_pct_of_world_population": round(float(pct), 1),
        },
    }

    print(f"Panel ({len(panel_countries)} countries) population, {YEAR}: "
          f"{panel_pop/1000:,.1f}M")
    print(f"World population, {YEAR}: {world_pop/1000:,.1f}M")
    print(f"Panel share of world population: {pct:.1f}%")

    write_checkin("panel_world_pop_share.json", out,
                  script_path="scripts/tables/panel_world_pop_share.py")


if __name__ == "__main__":
    main()
